apiVersion: v1
kind: pod
metadata:
  name: nginx
  namespace: roboshop
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80