apiVersion: v1
kind: Pod
metadata: 
  namespace: roboshop
  name: multi
  labels:
    env: prod
    app: web
spec:
  restartPolicy: never
  containers:
  - name: nginx
    image: nginx:latest
  - name: sidecar
    image: almalinux:8
    command: ["sleep","200"]



