apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    app: nginx
    environment: production
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80