apiVersion: v1
kind: pod
metadata:
  name: labels
  labels:
    app: nginx
    environment: production
spec:
  conatainers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80