apiVersion: v1
kind: Pod
metadata:
  name: annotations
  annotations:
    com.project.author: deepak
    com.project.name: roboshop
    com.project.version: v1.0
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - conatinerPort: 80