apiVersion: v1
kind: Pod
metadata:
  namespace: roboshop
  name: resources
  labels:
    env: prod
    project: roboshop
spec: 
  containers:
  - name: nginx
    image: nginx:latest
    containerPorts: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"