apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      env:
        - name: COURSE
          valueFrom: 
            configMapKeyRef:
              name: configmap
              key: COURSE
        - name: Duration
          valueFrom:
           configMapKeyRef:
              name: configmap
              key: DURATION
        - name: TRAINER
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: TRAINER   