apiVersion: v1
kind: pod
metadata:
  name: config-pod-direct
spec:
   containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: configmap
