apiVersion: v1
kind: Secret
metadata:
  name: secrets
data:
  username: ZGVlcGFr
  password: MTdrYjFhMDI3MUBE

---

apiVersion: v1
kind: Pod
metadata:
  name: secretpod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      envFrom:
        - secretRef:
            name: secrets
