apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: robos
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
      app: nginx
      environment: production
  template:
    metadata:
      name: frontend
      labels:
        app: robos
        tier: frontend
        environment: production
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: production
            - name: VERSION
              value: v1.0
            - name: AUTHOR
              value: deepak