apiVersion: v1
kind: PersistentVolume
metadata: 
  name: ebs-static
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-041e295294ca3f829
  capacity:
    storage: 20Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: static-ebs
spec:
  storageClassName: ""
  accessModes: 
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ng
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: front
      env: prd
  template:
    metadata:
      name: ngs
      labels:
        tier: front
        env: prd
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-html
          mountPath: "/usr/share/nginx/html"
      volumes:
      - name: nginx-html
        persistentVolumeClaim:
          claimName: static-ebs  
